/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Status */
        get: operations["auth_status_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/metrics/accuracy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Accuracy Metrics
         * @description Plain SQL accuracy / learning metrics (Phase 11 chart source).
         *
         *     Scoped to the same owner as the Recent-runs list when one is known (auth
         *     session, or an explicit query param), so this card and "Recent" never show
         *     two different populations side by side without saying so.
         */
        get: operations["get_accuracy_metrics_runs_metrics_accuracy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/approvers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approvers
         * @description Distinct approver identities, for the history page's filter dropdown.
         */
        get: operations["list_approvers_runs_approvers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Volume
         * @description Daily run counts over the whole history, not just one page.
         *
         *     Splits each day into runs that succeeded and runs that failed or were
         *     cancelled, so the chart's two series mean something specific. Days with no
         *     runs are returned as explicit zeroes rather than omitted, so the caller
         *     doesn't have to reconstruct the calendar.
         */
        get: operations["get_run_volume_runs_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity Feed
         * @description Merged, reverse-chronological stream of what actually happened.
         *
         *     Every entry is derived from a persisted timestamp (run created, prediction
         *     written, approval recorded, shadow started/measured, grade written, memory
         *     stored). Nothing is synthesized. Scoped to the same owner as the Recent
         *     list so the Overview never mixes two populations.
         */
        get: operations["get_activity_feed_runs_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/debug/demo-with-db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Debug Demo With Db
         * @description Developer helper: real customer_demo RO DB + sample migration SQL.
         *
         *     Reads the URL from env ``DEMO_READONLY_DATABASE_URL`` or repo file
         *     ``.judge_ro_database_url`` (server-side only). Creates the run, stores a
         *     connection secret, and runs schema discovery so predict/shadow can proceed.
         *
         *     Easy to remove: delete this route + the frontend Developer mode button.
         */
        post: operations["create_debug_demo_with_db_runs_debug_demo_with_db_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/debug/fake-migration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Debug Fake Migration
         * @description Debug helper: random SQL + synthetic schema so predict works without a real DB.
         *
         *     Stores a connection_secret_arn (control-plane DATABASE_URL) so approve can
         *     start Step Functions. DiscoverSchema is skipped because discovery already
         *     SUCCEEDED on the synthetic snapshot. Does not create graded memories.
         */
        post: operations["create_debug_fake_migration_runs_debug_fake_migration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Discard Run
         * @description Discard a run abandoned during setup.
         *
         *     Only a ``pending`` run with no approval, grade, execution result, shadow
         *     cluster or memory can be removed — see
         *     MigrationRunService.discard_abandoned_run. Anything further along is part
         *     of the audit record and returns 409 instead.
         */
        delete: operations["discard_run_runs__run_id__delete"];
        options?: never;
        head?: never;
        /** Update Run Status */
        patch: operations["update_run_status_runs__run_id__patch"];
        trace?: never;
    };
    "/runs/{run_id}/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Schema
         * @description Discover customer schema (read-only) and store connection_secret_arn pointer.
         */
        post: operations["discover_schema_runs__run_id__discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Prediction Pipeline
         * @description Run Phase 9 policy → predict → recommend and stop at awaiting_approval.
         */
        post: operations["run_prediction_pipeline_runs__run_id__predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/pipeline-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Progress
         * @description Live stage progress for a long-running predict / discover / local-verify
         *     (in-process, single-uvicorn-worker).
         *
         *     Predict progress is cleared once the run leaves ``predicting``; discover
         *     progress is only meaningful while the run is still ``pending`` (discovery
         *     never changes run status itself). Either way, a stale bar from a previous
         *     stage never survives a status change it doesn't belong to.
         */
        get: operations["get_pipeline_progress_runs__run_id__pipeline_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Run
         * @description Record approval. On proceed, auto-starts the verify workflow when configured.
         */
        post: operations["approve_run_runs__run_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/closed-loop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Closed Loop
         * @description Predict (if needed) → proceed → start SFN when ARN + connection secret exist.
         */
        post: operations["run_closed_loop_runs__run_id__closed_loop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/start-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Workflow
         * @description Start Step Functions verify after prediction + proceed approval.
         */
        post: operations["start_workflow_runs__run_id__start_workflow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/verify-local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Local
         * @description Run in-process mock shadow verify when Step Functions is not deployed.
         *
         *     Same handler chain as the durable workflow (discover → provision → load →
         *     execute → collect → persist/grade → cleanup), using SHADOW_PROVIDER=mock.
         *     Use this for local demos; set MIGRATION_WORKFLOW_ARN for real AWS verify.
         */
        post: operations["verify_local_runs__run_id__verify_local_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/sync-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Workflow */
        post: operations["sync_workflow_runs__run_id__sync_workflow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/abort-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abort Workflow
         * @description Abort a running shadow workflow and tear down the shadow cluster.
         */
        post: operations["abort_workflow_runs__run_id__abort_workflow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_runs__run_id__approval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Grade */
        get: operations["get_grade_runs__run_id__grade_get"];
        put?: never;
        /** Grade Run */
        post: operations["grade_run_runs__run_id__grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory */
        get: operations["get_memory_runs__run_id__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/shadow-cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shadow Cluster
         * @description Read-only shadow cluster lifecycle row (Phase 7 data; Phase 11 exposure).
         */
        get: operations["get_shadow_cluster_runs__run_id__shadow_cluster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/shadow-cluster/teardown-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Teardown Shadow Cluster Now
         * @description End a HOLDING cluster's inspection window immediately.
         *
         *     After execute+measure finish, the cluster is held (not destroyed) for
         *     ``settings.shadow_hold_minutes`` so the row-sample/schema-diff box stays
         *     populated — see app.lambdas.handlers.cleanup. This lets the user end that
         *     hold early instead of waiting out the window or the sweeper. Idempotent:
         *     calling it on an already-destroyed cluster just returns its current state.
         */
        post: operations["teardown_shadow_cluster_now_runs__run_id__shadow_cluster_teardown_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/shadow-cluster/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Shadow Cluster
         * @description Push-based shadow-cluster updates (SSE) — replaces polling GET /shadow-cluster.
         *
         *     One JSON `ShadowClusterResponse` payload per `event: shadow` message,
         *     sent only when it actually changed (plus a periodic heartbeat so proxies
         *     don't time out an idle connection). Falls back gracefully: a client that
         *     can't use EventSource can keep polling the plain GET route, which is
         *     unaffected by this endpoint's existence.
         */
        get: operations["stream_shadow_cluster_runs__run_id__shadow_cluster_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/execution-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Execution Result
         * @description Read-only shadow execution actuals (Phase 8 data; Phase 11 exposure).
         */
        get: operations["get_execution_result_runs__run_id__execution_result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/model-traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Traces
         * @description Durable Bedrock traces from explainability (prediction + recommendation).
         */
        get: operations["get_model_traces_runs__run_id__model_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/memories/repair-embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repair Embeddings */
        post: operations["repair_embeddings_runs_memories_repair_embeddings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Corpus Health
         * @description Structured corpus health for terminal + UI. Loud about problems.
         */
        get: operations["get_corpus_health_memories_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse Memories */
        get: operations["browse_memories_memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Memories
         * @description Semantic search over graded memories, on the CockroachDB distributed
         *     vector index.
         *
         *     ``scope``:
         *       * ``corpus`` — the shared open-source corpus only (no owner predicate,
         *         rides the no-prefix partial index)
         *       * ``mine`` — this owner's graded runs only
         *       * ``all`` — both, which is what prediction-time retrieval uses
         */
        post: operations["search_memories_memories_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/corpus-identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Corpus Identity
         * @description Expose the reserved corpus owner constant for UI filters.
         */
        get: operations["get_corpus_identity_memories_corpus_identity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalCreateRequest */
        ApprovalCreateRequest: {
            decision: components["schemas"]["ApprovalDecision"];
            /** Approver Identity */
            approver_identity: string;
            /** Override Rationale */
            override_rationale?: string | null;
            /** Connection Secret Arn */
            connection_secret_arn?: string | null;
            /**
             * Start Workflow
             * @description Override auto-start of SFN on proceed (default: server auto)
             */
            start_workflow?: boolean | null;
        };
        /**
         * ApprovalDecision
         * @description Human decision at the Phase 9 approval gate.
         * @enum {string}
         */
        ApprovalDecision: "proceed" | "accept_recommended" | "cancel";
        /** ApprovalResponse */
        ApprovalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Approver Identity */
            approver_identity: string;
            decision: components["schemas"]["ApprovalDecision"];
            /** Override Rationale */
            override_rationale: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AuthLoginRequest */
        AuthLoginRequest: {
            /** Owner Identity */
            owner_identity: string;
            /** Password */
            password: string;
        };
        /** AuthMeResponse */
        AuthMeResponse: {
            /** Owner Identity */
            owner_identity: string;
            /** Auth Enabled */
            auth_enabled: boolean;
            /** Display Name */
            display_name?: string | null;
        };
        /** AuthRegisterRequest */
        AuthRegisterRequest: {
            /** Owner Identity */
            owner_identity: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** AuthTokenResponse */
        AuthTokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Owner Identity */
            owner_identity: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /**
         * ClosedLoopRequest
         * @description Drive the operator happy path from a single POST.
         */
        ClosedLoopRequest: {
            /**
             * Approver Identity
             * @default closed-loop
             */
            approver_identity: string;
            /** Connection Secret Arn */
            connection_secret_arn?: string | null;
            /** Override Rationale */
            override_rationale?: string | null;
            /**
             * Start Workflow
             * @default true
             */
            start_workflow: boolean;
        };
        /**
         * CompatibilityRisk
         * @description Whether the change breaks application code that has not been deployed yet.
         * @enum {string}
         */
        CompatibilityRisk: "low" | "medium" | "high";
        /**
         * DiscoverSchemaRequest
         * @description Discover schema for a run and optionally register the connection secret.
         *
         *     Provide either ``connection_secret_arn`` (preferred — password stays in
         *     Secrets Manager / local secret store) or a one-shot ``database_url`` which
         *     is stored under a run-scoped secret name and never persisted on the row.
         */
        DiscoverSchemaRequest: {
            /** Connection Secret Arn */
            connection_secret_arn?: string | null;
            /**
             * Database Url
             * @description One-shot connection URL; stored as a secret, never on the run row
             */
            database_url?: string | null;
        };
        /** ExecutionResultResponse */
        ExecutionResultResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Success */
            success: boolean;
            /** Actual Duration Seconds */
            actual_duration_seconds: number;
            /** Actual Storage Mb */
            actual_storage_mb: number;
            /** Error Message */
            error_message?: string | null;
            /** Rollback Required */
            rollback_required: boolean;
            /** Timed Out */
            timed_out: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GradeResponse */
        GradeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Scale Tier */
            scale_tier: string;
            /** Timed Out */
            timed_out: boolean;
            /** Duration Abs Error Seconds */
            duration_abs_error_seconds?: number | null;
            /** Duration Pct Error */
            duration_pct_error?: number | null;
            /** Duration Within Band */
            duration_within_band?: boolean | null;
            /** Duration Unverifiable */
            duration_unverifiable: boolean;
            /** Storage Abs Error Mb */
            storage_abs_error_mb: number;
            /** Storage Pct Error */
            storage_pct_error?: number | null;
            /** Storage Within Band */
            storage_within_band?: boolean | null;
            /**
             * Storage Unverifiable
             * @default false
             */
            storage_unverifiable: boolean;
            /** Rollback Predicted */
            rollback_predicted: string;
            /** Rollback Actual Class */
            rollback_actual_class: string;
            /** Rollback Consistent */
            rollback_consistent: boolean;
            /** Rollback Within Band */
            rollback_within_band: boolean;
            /** Outcome Class */
            outcome_class: string;
            /** High Risk Flags Present */
            high_risk_flags_present: boolean;
            /** Adjusted Confidence */
            adjusted_confidence: number;
            /** Scalar Accuracy Score */
            scalar_accuracy_score: number;
            /** Dimension Details */
            dimension_details: {
                [key: string]: unknown;
            };
            /** Surprise Notes */
            surprise_notes?: string | null;
            /** Lessons Learned */
            lessons_learned: string;
            /** Prose Status */
            prose_status: string;
            /** Prose Error */
            prose_error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MemoryListItem */
        MemoryListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Owner Identity */
            owner_identity: string;
            /** Scale Tier */
            scale_tier: string;
            /** Migration Type */
            migration_type: string;
            /** Migration Summary */
            migration_summary: string;
            /** Schema Summary */
            schema_summary: string;
            /** Lessons Learned */
            lessons_learned: string;
            /** Surprise Notes */
            surprise_notes?: string | null;
            /** Embed Text */
            embed_text: string;
            /** Embedding Status */
            embedding_status: string;
            /** Embedding Error */
            embedding_error?: string | null;
            /** Embedding Model Id */
            embedding_model_id?: string | null;
            /**
             * Has Embedding
             * @default false
             */
            has_embedding: boolean;
            /** Scalar Accuracy Score */
            scalar_accuracy_score?: number | null;
            /**
             * Not A Graded Run
             * @default false
             */
            not_a_graded_run: boolean;
            /** Source Url */
            source_url?: string | null;
            /** Ui Label */
            ui_label?: string | null;
            /** Integrity Kind */
            integrity_kind?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MemoryListResponse */
        MemoryListResponse: {
            /** Items */
            items: components["schemas"]["MemoryListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Health */
            health: {
                [key: string]: unknown;
            };
        };
        /** MemoryResponse */
        MemoryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Owner Identity */
            owner_identity: string;
            /** Scale Tier */
            scale_tier: string;
            /** Migration Type */
            migration_type: string;
            /** Migration Summary */
            migration_summary: string;
            /** Schema Summary */
            schema_summary: string;
            /** Lessons Learned */
            lessons_learned: string;
            /** Surprise Notes */
            surprise_notes?: string | null;
            /** Embed Text */
            embed_text: string;
            /** Embedding Status */
            embedding_status: string;
            /** Embedding Error */
            embedding_error?: string | null;
            /** Embedding Model Id */
            embedding_model_id?: string | null;
            /** Scalar Accuracy Score */
            scalar_accuracy_score?: number | null;
            /**
             * Not A Graded Run
             * @default false
             */
            not_a_graded_run: boolean;
            /** Source Url */
            source_url?: string | null;
            /** Ui Label */
            ui_label?: string | null;
            /** Integrity Kind */
            integrity_kind?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MemorySearchHit
         * @description One ranked memory. Carries the same integrity markers as the browse and
         *     retrieval paths so a seeded open-source corpus entry can never be mistaken
         *     for a real graded run.
         */
        MemorySearchHit: {
            /**
             * Memory Id
             * Format: uuid
             */
            memory_id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Similarity Score */
            similarity_score: number;
            /** Owner Identity */
            owner_identity: string;
            /** Migration Type */
            migration_type: string;
            /** Scale Tier */
            scale_tier: string;
            /** Migration Summary */
            migration_summary: string;
            /** Lessons Learned */
            lessons_learned: string;
            /** Surprise Notes */
            surprise_notes?: string | null;
            /** Outcome Class */
            outcome_class?: string | null;
            /** Execution Success */
            execution_success?: boolean | null;
            /** Predicted Duration Seconds */
            predicted_duration_seconds?: number | null;
            /** Actual Duration Seconds */
            actual_duration_seconds?: number | null;
            /** Predicted Storage Mb */
            predicted_storage_mb?: number | null;
            /** Actual Storage Mb */
            actual_storage_mb?: number | null;
            /** Scalar Accuracy Score */
            scalar_accuracy_score?: number | null;
            /** Memory Origin */
            memory_origin?: string | null;
            /**
             * Not A Graded Run
             * @default false
             */
            not_a_graded_run: boolean;
            /** Source Url */
            source_url?: string | null;
            /** Ui Label */
            ui_label?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MemorySearchRequest
         * @description Free-text semantic search over graded memories.
         */
        MemorySearchRequest: {
            /** Query */
            query: string;
            /**
             * Scope
             * @default all
             * @enum {string}
             */
            scope: "mine" | "corpus" | "all";
            /** Migration Type */
            migration_type?: string | null;
            /** Scale Tier */
            scale_tier?: string | null;
            /**
             * Min Similarity
             * @default 0
             */
            min_similarity: number;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** MemorySearchResponse */
        MemorySearchResponse: {
            /** Query */
            query: string;
            /** Scope */
            scope: string;
            /** Embedding Model Id */
            embedding_model_id?: string | null;
            /** Index Used */
            index_used: string | null;
            /** Took Ms */
            took_ms: number;
            /** Total */
            total: number;
            /** Results */
            results: components["schemas"]["MemorySearchHit"][];
        };
        /** MigrationRunCreateRequest */
        MigrationRunCreateRequest: {
            /**
             * Migration Sql
             * @description SQL migration to analyze
             */
            migration_sql: string;
            /**
             * Owner Identity
             * @description Soft owner identity (no real auth yet); scopes memory retrieval
             * @default anonymous
             */
            owner_identity: string;
            /**
             * Revises Run Id
             * @description Optional link to an earlier run this migration revises
             */
            revises_run_id?: string | null;
            /**
             * Run Kind
             * @description standard (default) | chaos (deliberate failure test) | debug (developer/demo tooling). Keeps chaos/debug runs out of the default Recent list and future accuracy queries.
             * @default standard
             */
            run_kind: string;
        };
        /** MigrationRunListResponse */
        MigrationRunListResponse: {
            /** Items */
            items: components["schemas"]["MigrationRunSummaryResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** MigrationRunResponse */
        MigrationRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Migration Sql */
            migration_sql: string;
            status: components["schemas"]["MigrationRunStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Owner Identity
             * @default anonymous
             */
            owner_identity: string;
            /**
             * Run Kind
             * @default standard
             */
            run_kind: string;
            /** Revises Run Id */
            revises_run_id?: string | null;
            /** Schema Snapshot */
            schema_snapshot?: {
                [key: string]: unknown;
            } | null;
            /** Schema Discovered At */
            schema_discovered_at?: string | null;
            /** Schema Discovery Duration Ms */
            schema_discovery_duration_ms?: number | null;
            /** Schema Database Engine */
            schema_database_engine?: string | null;
            /** Schema Database Version */
            schema_database_version?: string | null;
            schema_discovery_status?: components["schemas"]["SchemaDiscoveryStatus"] | null;
            /** Sfn Execution Arn */
            sfn_execution_arn?: string | null;
            /** Connection Secret Arn */
            connection_secret_arn?: string | null;
            /** @default not_started */
            workflow_status: components["schemas"]["WorkflowStatus"];
            /** Workflow Started At */
            workflow_started_at?: string | null;
            /** Workflow Finished At */
            workflow_finished_at?: string | null;
            /** Risk Flags */
            risk_flags?: {
                [key: string]: unknown;
            }[] | null;
            compatibility_risk?: components["schemas"]["CompatibilityRisk"] | null;
            /** Requires Expand Contract */
            requires_expand_contract?: boolean | null;
            /** Requires Manual Review */
            requires_manual_review?: boolean | null;
            policy_decision?: components["schemas"]["PolicyDecision"] | null;
            /** Parsed Statement Types */
            parsed_statement_types?: string[] | null;
            /** Recommendation */
            recommendation?: {
                [key: string]: unknown;
            } | null;
            /** Explainability */
            explainability?: {
                [key: string]: unknown;
            } | null;
            /** Prediction Scale Tier */
            prediction_scale_tier?: string | null;
            /** Recommendation Outcome */
            recommendation_outcome?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * MigrationRunStatus
         * @enum {string}
         */
        MigrationRunStatus: "pending" | "predicting" | "awaiting_approval" | "running" | "completed" | "failed";
        /** MigrationRunStatusUpdateRequest */
        MigrationRunStatusUpdateRequest: {
            status: components["schemas"]["MigrationRunStatus"];
        };
        /**
         * MigrationRunSummaryResponse
         * @description List item without the large JSONB schema snapshot.
         *
         *     Carries a flattened slice of the run's approval / grade / execution-result /
         *     shadow-cluster children so a history table can render risk, confidence,
         *     duration, approver, shadow outcome and graded state without N follow-up
         *     requests per row. Populated by :meth:`from_orm_run`; the children are
         *     batch-loaded via ``load_summary_children`` in the repository.
         */
        MigrationRunSummaryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Migration Sql */
            migration_sql: string;
            status: components["schemas"]["MigrationRunStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Owner Identity
             * @default anonymous
             */
            owner_identity: string;
            /**
             * Run Kind
             * @default standard
             */
            run_kind: string;
            /** Revises Run Id */
            revises_run_id?: string | null;
            /** Schema Discovered At */
            schema_discovered_at?: string | null;
            /** Schema Discovery Duration Ms */
            schema_discovery_duration_ms?: number | null;
            /** Schema Database Engine */
            schema_database_engine?: string | null;
            /** Schema Database Version */
            schema_database_version?: string | null;
            schema_discovery_status?: components["schemas"]["SchemaDiscoveryStatus"] | null;
            /** Sfn Execution Arn */
            sfn_execution_arn?: string | null;
            /** @default not_started */
            workflow_status: components["schemas"]["WorkflowStatus"];
            /** Workflow Started At */
            workflow_started_at?: string | null;
            /** Workflow Finished At */
            workflow_finished_at?: string | null;
            policy_decision?: components["schemas"]["PolicyDecision"] | null;
            /** Requires Manual Review */
            requires_manual_review?: boolean | null;
            /** Prediction Scale Tier */
            prediction_scale_tier?: string | null;
            compatibility_risk?: components["schemas"]["CompatibilityRisk"] | null;
            /** Confidence Score */
            confidence_score?: number | null;
            /** Approval Decision */
            approval_decision?: string | null;
            /** Approver Identity */
            approver_identity?: string | null;
            /** Approved At */
            approved_at?: string | null;
            /** Actual Duration Seconds */
            actual_duration_seconds?: number | null;
            /** Actual Storage Mb */
            actual_storage_mb?: number | null;
            /** Execution Success */
            execution_success?: boolean | null;
            /** Execution Timed Out */
            execution_timed_out?: boolean | null;
            /** Outcome Class */
            outcome_class?: string | null;
            /** Scalar Accuracy Score */
            scalar_accuracy_score?: number | null;
            /**
             * Is Graded
             * @default false
             */
            is_graded: boolean;
            /** Shadow Status */
            shadow_status?: string | null;
            /** Shadow Provider */
            shadow_provider?: string | null;
            /** Has Schema Snapshot */
            readonly has_schema_snapshot: boolean;
            /**
             * Shadow Outcome
             * @description pass | warn | fail — or None when no shadow execution happened.
             *
             *     Derived only from measured facts: whether the shadow execution
             *     succeeded, whether it timed out, whether the cluster itself failed,
             *     and the grader's outcome_class. Never inferred from risk or confidence.
             */
            readonly shadow_outcome: string | null;
            /** Is Terminal */
            readonly is_terminal: boolean;
            /** Sql Snippet */
            readonly sql_snippet: string;
        };
        /**
         * PolicyDecision
         * @description Deterministic policy outcome. Authoritative over the model.
         * @enum {string}
         */
        PolicyDecision: "allow" | "allow_with_warning" | "block";
        /** RepairEmbeddingsRequest */
        RepairEmbeddingsRequest: {
            /** Memory Id */
            memory_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /**
         * SchemaDiscoveryStatus
         * @enum {string}
         */
        SchemaDiscoveryStatus: "pending" | "succeeded" | "failed" | "rejected";
        /** ShadowClusterResponse */
        ShadowClusterResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Cluster Id */
            cluster_id?: string | null;
            /** Cluster Name */
            cluster_name?: string | null;
            /** Provider */
            provider: string;
            /** Region */
            region: string;
            /** Status */
            status: string;
            /** Scale Tier */
            scale_tier?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Stage Timings */
            stage_timings?: {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message?: string | null;
            /** Destroyed At */
            destroyed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Event Log */
            event_log?: {
                [key: string]: unknown;
            }[] | null;
            /** Schema Snapshot Before */
            schema_snapshot_before?: {
                [key: string]: unknown;
            } | null;
            /** Schema Snapshot After */
            schema_snapshot_after?: {
                [key: string]: unknown;
            } | null;
            /** Schema Diff */
            schema_diff?: {
                [key: string]: unknown;
            } | null;
            /** Row Sample Before */
            row_sample_before?: {
                [key: string]: unknown;
            } | null;
            /** Row Sample After */
            row_sample_after?: {
                [key: string]: unknown;
            } | null;
        };
        /** StartWorkflowRequest */
        StartWorkflowRequest: {
            /**
             * Connection Secret Arn
             * @description Override; defaults to the ARN stored on the run
             */
            connection_secret_arn?: string | null;
            /**
             * Database Url
             * @description One-shot read-only URL when the run has no connection_secret_arn yet (same store path as POST /discover)
             */
            database_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowStatus
         * @description Durable Step Functions execution status mirrored in CockroachDB.
         * @enum {string}
         */
        WorkflowStatus: "not_started" | "running" | "succeeded" | "failed" | "timed_out" | "aborted";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    auth_status_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["MigrationRunStatus"] | null;
                owner_identity?: string | null;
                run_kind?: string | null;
                /** @description Comma-separated run_kind values to exclude, e.g. chaos,debug */
                exclude_kinds?: string | null;
                /** @description Case-insensitive substring match on the migration SQL. */
                q?: string | null;
                /** @description Filter by compatibility_risk: low | medium | high */
                risk?: string | null;
                /** @description Filter by recorded approval decision: proceed | accept_recommended | cancel, or 'none' for runs with no decision yet. */
                decision?: string | null;
                approver?: string | null;
                /** @description created_at | updated_at | status | compatibility_risk */
                order_by?: string;
                order_dir?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrationRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_accuracy_metrics_runs_metrics_accuracy_get: {
        parameters: {
            query?: {
                owner_identity?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvers_runs_approvers_get: {
        parameters: {
            query?: {
                owner_identity?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_volume_runs_volume_get: {
        parameters: {
            query?: {
                owner_identity?: string | null;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_feed_runs_activity_get: {
        parameters: {
            query?: {
                owner_identity?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_debug_demo_with_db_runs_debug_demo_with_db_post: {
        parameters: {
            query?: {
                owner_identity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_debug_fake_migration_runs_debug_fake_migration_post: {
        parameters: {
            query?: {
                owner_identity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_run_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_run_status_runs__run_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrationRunStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_schema_runs__run_id__discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverSchemaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_prediction_pipeline_runs__run_id__predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_progress_runs__run_id__pipeline_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_run_runs__run_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_closed_loop_runs__run_id__closed_loop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosedLoopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workflow_runs__run_id__start_workflow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartWorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_local_runs__run_id__verify_local_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_workflow_runs__run_id__sync_workflow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_workflow_runs__run_id__abort_workflow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_runs__run_id__approval_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_grade_runs__run_id__grade_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grade_run_runs__run_id__grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_runs__run_id__memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shadow_cluster_runs__run_id__shadow_cluster_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShadowClusterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    teardown_shadow_cluster_now_runs__run_id__shadow_cluster_teardown_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShadowClusterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_shadow_cluster_runs__run_id__shadow_cluster_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_result_runs__run_id__execution_result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_traces_runs__run_id__model_traces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_embeddings_runs_memories_repair_embeddings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairEmbeddingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_corpus_health_memories_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    browse_memories_memories_get: {
        parameters: {
            query?: {
                /** @description Filter by owner. Use the reserved corpus owner identity (CORPUS_OWNER_IDENTITY) for the shared open-source corpus. */
                owner_identity?: string | null;
                embedding_status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_memories_memories_search_post: {
        parameters: {
            query?: {
                /** @description Owner to scope 'mine'/'all' to. Ignored when auth is enforced — the token's owner wins. */
                owner_identity?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemorySearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_corpus_identity_memories_corpus_identity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
