/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/metrics/accuracy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Accuracy Metrics
         * @description Plain SQL accuracy / learning metrics (Phase 11 chart source).
         */
        get: operations["get_accuracy_metrics_runs_metrics_accuracy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/debug/fake-migration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Debug Fake Migration
         * @description Debug helper: random SQL + synthetic schema so predict works without a real DB.
         *
         *     Stores a connection_secret_arn (control-plane DATABASE_URL) so approve can
         *     start Step Functions. DiscoverSchema is skipped because discovery already
         *     SUCCEEDED on the synthetic snapshot. Does not create graded memories.
         */
        post: operations["create_debug_fake_migration_runs_debug_fake_migration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Run Status */
        patch: operations["update_run_status_runs__run_id__patch"];
        trace?: never;
    };
    "/runs/{run_id}/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Schema
         * @description Discover customer schema (read-only) and store connection_secret_arn pointer.
         */
        post: operations["discover_schema_runs__run_id__discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Prediction Pipeline
         * @description Run Phase 9 policy → predict → recommend and stop at awaiting_approval.
         */
        post: operations["run_prediction_pipeline_runs__run_id__predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/pipeline-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Progress
         * @description Live stage progress for a long-running predict / local-verify (in-process).
         */
        get: operations["get_pipeline_progress_runs__run_id__pipeline_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Run
         * @description Record approval. On proceed, auto-starts the verify workflow when configured.
         */
        post: operations["approve_run_runs__run_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/closed-loop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Closed Loop
         * @description Predict (if needed) → proceed → start SFN when ARN + connection secret exist.
         */
        post: operations["run_closed_loop_runs__run_id__closed_loop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/start-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Workflow
         * @description Start Step Functions verify after prediction + proceed approval.
         */
        post: operations["start_workflow_runs__run_id__start_workflow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/verify-local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Local
         * @description Run in-process mock shadow verify when Step Functions is not deployed.
         *
         *     Same handler chain as the durable workflow (discover → provision → load →
         *     execute → collect → persist/grade → cleanup), using SHADOW_PROVIDER=mock.
         *     Use this for local demos; set MIGRATION_WORKFLOW_ARN for real AWS verify.
         */
        post: operations["verify_local_runs__run_id__verify_local_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/sync-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Workflow */
        post: operations["sync_workflow_runs__run_id__sync_workflow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_runs__run_id__approval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Grade */
        get: operations["get_grade_runs__run_id__grade_get"];
        put?: never;
        /** Grade Run */
        post: operations["grade_run_runs__run_id__grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory */
        get: operations["get_memory_runs__run_id__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/shadow-cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shadow Cluster
         * @description Read-only shadow cluster lifecycle row (Phase 7 data; Phase 11 exposure).
         */
        get: operations["get_shadow_cluster_runs__run_id__shadow_cluster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/execution-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Execution Result
         * @description Read-only shadow execution actuals (Phase 8 data; Phase 11 exposure).
         */
        get: operations["get_execution_result_runs__run_id__execution_result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/model-traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Traces
         * @description Durable Bedrock traces from explainability (prediction + recommendation).
         */
        get: operations["get_model_traces_runs__run_id__model_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/memories/repair-embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repair Embeddings */
        post: operations["repair_embeddings_runs_memories_repair_embeddings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Corpus Health
         * @description Structured corpus health for terminal + UI. Loud about problems.
         */
        get: operations["get_corpus_health_memories_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse Memories */
        get: operations["browse_memories_memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/corpus-identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Corpus Identity
         * @description Expose the reserved corpus owner constant for UI filters.
         */
        get: operations["get_corpus_identity_memories_corpus_identity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalCreateRequest */
        ApprovalCreateRequest: {
            decision: components["schemas"]["ApprovalDecision"];
            /** Approver Identity */
            approver_identity: string;
            /** Override Rationale */
            override_rationale?: string | null;
            /** Connection Secret Arn */
            connection_secret_arn?: string | null;
            /**
             * Start Workflow
             * @description Override auto-start of SFN on proceed (default: server auto)
             */
            start_workflow?: boolean | null;
        };
        /**
         * ApprovalDecision
         * @description Human decision at the Phase 9 approval gate.
         * @enum {string}
         */
        ApprovalDecision: "proceed" | "accept_recommended" | "cancel";
        /** ApprovalResponse */
        ApprovalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Approver Identity */
            approver_identity: string;
            decision: components["schemas"]["ApprovalDecision"];
            /** Override Rationale */
            override_rationale: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ClosedLoopRequest
         * @description Drive the operator happy path from a single POST.
         */
        ClosedLoopRequest: {
            /**
             * Approver Identity
             * @default closed-loop
             */
            approver_identity: string;
            /** Connection Secret Arn */
            connection_secret_arn?: string | null;
            /** Override Rationale */
            override_rationale?: string | null;
            /**
             * Start Workflow
             * @default true
             */
            start_workflow: boolean;
        };
        /**
         * CompatibilityRisk
         * @description Whether the change breaks application code that has not been deployed yet.
         * @enum {string}
         */
        CompatibilityRisk: "low" | "medium" | "high";
        /**
         * DiscoverSchemaRequest
         * @description Discover schema for a run and optionally register the connection secret.
         *
         *     Provide either ``connection_secret_arn`` (preferred — password stays in
         *     Secrets Manager / local secret store) or a one-shot ``database_url`` which
         *     is stored under a run-scoped secret name and never persisted on the row.
         */
        DiscoverSchemaRequest: {
            /** Connection Secret Arn */
            connection_secret_arn?: string | null;
            /**
             * Database Url
             * @description One-shot connection URL; stored as a secret, never on the run row
             */
            database_url?: string | null;
        };
        /** ExecutionResultResponse */
        ExecutionResultResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Success */
            success: boolean;
            /** Actual Duration Seconds */
            actual_duration_seconds: number;
            /** Actual Storage Mb */
            actual_storage_mb: number;
            /** Error Message */
            error_message?: string | null;
            /** Rollback Required */
            rollback_required: boolean;
            /** Timed Out */
            timed_out: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GradeResponse */
        GradeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Scale Tier */
            scale_tier: string;
            /** Timed Out */
            timed_out: boolean;
            /** Duration Abs Error Seconds */
            duration_abs_error_seconds?: number | null;
            /** Duration Pct Error */
            duration_pct_error?: number | null;
            /** Duration Within Band */
            duration_within_band?: boolean | null;
            /** Duration Unverifiable */
            duration_unverifiable: boolean;
            /** Storage Abs Error Mb */
            storage_abs_error_mb: number;
            /** Storage Pct Error */
            storage_pct_error?: number | null;
            /** Storage Within Band */
            storage_within_band: boolean;
            /** Rollback Predicted */
            rollback_predicted: string;
            /** Rollback Actual Class */
            rollback_actual_class: string;
            /** Rollback Consistent */
            rollback_consistent: boolean;
            /** Rollback Within Band */
            rollback_within_band: boolean;
            /** Outcome Class */
            outcome_class: string;
            /** High Risk Flags Present */
            high_risk_flags_present: boolean;
            /** Adjusted Confidence */
            adjusted_confidence: number;
            /** Scalar Accuracy Score */
            scalar_accuracy_score: number;
            /** Dimension Details */
            dimension_details: {
                [key: string]: unknown;
            };
            /** Surprise Notes */
            surprise_notes?: string | null;
            /** Lessons Learned */
            lessons_learned: string;
            /** Prose Status */
            prose_status: string;
            /** Prose Error */
            prose_error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MemoryListItem */
        MemoryListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Owner Identity */
            owner_identity: string;
            /** Scale Tier */
            scale_tier: string;
            /** Migration Type */
            migration_type: string;
            /** Migration Summary */
            migration_summary: string;
            /** Schema Summary */
            schema_summary: string;
            /** Lessons Learned */
            lessons_learned: string;
            /** Surprise Notes */
            surprise_notes?: string | null;
            /** Embed Text */
            embed_text: string;
            /** Embedding Status */
            embedding_status: string;
            /** Embedding Error */
            embedding_error?: string | null;
            /** Embedding Model Id */
            embedding_model_id?: string | null;
            /**
             * Has Embedding
             * @default false
             */
            has_embedding: boolean;
            /** Scalar Accuracy Score */
            scalar_accuracy_score?: number | null;
            /**
             * Not A Graded Run
             * @default false
             */
            not_a_graded_run: boolean;
            /** Source Url */
            source_url?: string | null;
            /** Ui Label */
            ui_label?: string | null;
            /** Integrity Kind */
            integrity_kind?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MemoryListResponse */
        MemoryListResponse: {
            /** Items */
            items: components["schemas"]["MemoryListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Health */
            health: {
                [key: string]: unknown;
            };
        };
        /** MemoryResponse */
        MemoryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Owner Identity */
            owner_identity: string;
            /** Scale Tier */
            scale_tier: string;
            /** Migration Type */
            migration_type: string;
            /** Migration Summary */
            migration_summary: string;
            /** Schema Summary */
            schema_summary: string;
            /** Lessons Learned */
            lessons_learned: string;
            /** Surprise Notes */
            surprise_notes?: string | null;
            /** Embed Text */
            embed_text: string;
            /** Embedding Status */
            embedding_status: string;
            /** Embedding Error */
            embedding_error?: string | null;
            /** Embedding Model Id */
            embedding_model_id?: string | null;
            /** Scalar Accuracy Score */
            scalar_accuracy_score?: number | null;
            /**
             * Not A Graded Run
             * @default false
             */
            not_a_graded_run: boolean;
            /** Source Url */
            source_url?: string | null;
            /** Ui Label */
            ui_label?: string | null;
            /** Integrity Kind */
            integrity_kind?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MigrationRunCreateRequest */
        MigrationRunCreateRequest: {
            /**
             * Migration Sql
             * @description SQL migration to analyze
             */
            migration_sql: string;
            /**
             * Owner Identity
             * @description Soft owner identity (no real auth yet); scopes memory retrieval
             * @default anonymous
             */
            owner_identity: string;
            /**
             * Revises Run Id
             * @description Optional link to an earlier run this migration revises
             */
            revises_run_id?: string | null;
        };
        /** MigrationRunListResponse */
        MigrationRunListResponse: {
            /** Items */
            items: components["schemas"]["MigrationRunSummaryResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** MigrationRunResponse */
        MigrationRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Migration Sql */
            migration_sql: string;
            status: components["schemas"]["MigrationRunStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Owner Identity
             * @default anonymous
             */
            owner_identity: string;
            /** Revises Run Id */
            revises_run_id?: string | null;
            /** Schema Snapshot */
            schema_snapshot?: {
                [key: string]: unknown;
            } | null;
            /** Schema Discovered At */
            schema_discovered_at?: string | null;
            /** Schema Discovery Duration Ms */
            schema_discovery_duration_ms?: number | null;
            /** Schema Database Engine */
            schema_database_engine?: string | null;
            /** Schema Database Version */
            schema_database_version?: string | null;
            schema_discovery_status?: components["schemas"]["SchemaDiscoveryStatus"] | null;
            /** Sfn Execution Arn */
            sfn_execution_arn?: string | null;
            /** Connection Secret Arn */
            connection_secret_arn?: string | null;
            /** @default not_started */
            workflow_status: components["schemas"]["WorkflowStatus"];
            /** Workflow Started At */
            workflow_started_at?: string | null;
            /** Workflow Finished At */
            workflow_finished_at?: string | null;
            /** Risk Flags */
            risk_flags?: {
                [key: string]: unknown;
            }[] | null;
            compatibility_risk?: components["schemas"]["CompatibilityRisk"] | null;
            /** Requires Expand Contract */
            requires_expand_contract?: boolean | null;
            /** Requires Manual Review */
            requires_manual_review?: boolean | null;
            policy_decision?: components["schemas"]["PolicyDecision"] | null;
            /** Parsed Statement Types */
            parsed_statement_types?: string[] | null;
            /** Recommendation */
            recommendation?: {
                [key: string]: unknown;
            } | null;
            /** Explainability */
            explainability?: {
                [key: string]: unknown;
            } | null;
            /** Prediction Scale Tier */
            prediction_scale_tier?: string | null;
            /** Recommendation Outcome */
            recommendation_outcome?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * MigrationRunStatus
         * @enum {string}
         */
        MigrationRunStatus: "pending" | "predicting" | "awaiting_approval" | "running" | "completed" | "failed";
        /** MigrationRunStatusUpdateRequest */
        MigrationRunStatusUpdateRequest: {
            status: components["schemas"]["MigrationRunStatus"];
        };
        /**
         * MigrationRunSummaryResponse
         * @description List item without the large JSONB schema snapshot.
         */
        MigrationRunSummaryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Migration Sql */
            migration_sql: string;
            status: components["schemas"]["MigrationRunStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Owner Identity
             * @default anonymous
             */
            owner_identity: string;
            /** Revises Run Id */
            revises_run_id?: string | null;
            /** Schema Discovered At */
            schema_discovered_at?: string | null;
            /** Schema Discovery Duration Ms */
            schema_discovery_duration_ms?: number | null;
            /** Schema Database Engine */
            schema_database_engine?: string | null;
            /** Schema Database Version */
            schema_database_version?: string | null;
            schema_discovery_status?: components["schemas"]["SchemaDiscoveryStatus"] | null;
            /** Sfn Execution Arn */
            sfn_execution_arn?: string | null;
            /** @default not_started */
            workflow_status: components["schemas"]["WorkflowStatus"];
            /** Workflow Started At */
            workflow_started_at?: string | null;
            /** Workflow Finished At */
            workflow_finished_at?: string | null;
            policy_decision?: components["schemas"]["PolicyDecision"] | null;
            /** Requires Manual Review */
            requires_manual_review?: boolean | null;
            /** Prediction Scale Tier */
            prediction_scale_tier?: string | null;
            /** Has Schema Snapshot */
            readonly has_schema_snapshot: boolean;
            /** Is Terminal */
            readonly is_terminal: boolean;
            /** Sql Snippet */
            readonly sql_snippet: string;
        };
        /**
         * PolicyDecision
         * @description Deterministic policy outcome. Authoritative over the model.
         * @enum {string}
         */
        PolicyDecision: "allow" | "allow_with_warning" | "block";
        /** RepairEmbeddingsRequest */
        RepairEmbeddingsRequest: {
            /** Memory Id */
            memory_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /**
         * SchemaDiscoveryStatus
         * @enum {string}
         */
        SchemaDiscoveryStatus: "pending" | "succeeded" | "failed" | "rejected";
        /** ShadowClusterResponse */
        ShadowClusterResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Migration Run Id
             * Format: uuid
             */
            migration_run_id: string;
            /** Cluster Id */
            cluster_id?: string | null;
            /** Cluster Name */
            cluster_name?: string | null;
            /** Provider */
            provider: string;
            /** Region */
            region: string;
            /** Status */
            status: string;
            /** Scale Tier */
            scale_tier?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Stage Timings */
            stage_timings?: {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message?: string | null;
            /** Destroyed At */
            destroyed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StartWorkflowRequest */
        StartWorkflowRequest: {
            /**
             * Connection Secret Arn
             * @description Override; defaults to the ARN stored on the run
             */
            connection_secret_arn?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowStatus
         * @description Durable Step Functions execution status mirrored in CockroachDB.
         * @enum {string}
         */
        WorkflowStatus: "not_started" | "running" | "succeeded" | "failed" | "timed_out" | "aborted";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["MigrationRunStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrationRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_accuracy_metrics_runs_metrics_accuracy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_debug_fake_migration_runs_debug_fake_migration_post: {
        parameters: {
            query?: {
                owner_identity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_run_status_runs__run_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrationRunStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_schema_runs__run_id__discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverSchemaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_prediction_pipeline_runs__run_id__predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_progress_runs__run_id__pipeline_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_run_runs__run_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_closed_loop_runs__run_id__closed_loop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosedLoopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workflow_runs__run_id__start_workflow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartWorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_local_runs__run_id__verify_local_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_workflow_runs__run_id__sync_workflow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_runs__run_id__approval_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_grade_runs__run_id__grade_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grade_run_runs__run_id__grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_runs__run_id__memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shadow_cluster_runs__run_id__shadow_cluster_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShadowClusterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_result_runs__run_id__execution_result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_traces_runs__run_id__model_traces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_embeddings_runs_memories_repair_embeddings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairEmbeddingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_corpus_health_memories_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    browse_memories_memories_get: {
        parameters: {
            query?: {
                /** @description Filter by owner. Use the reserved corpus owner identity (CORPUS_OWNER_IDENTITY) for the shared open-source corpus. */
                owner_identity?: string | null;
                embedding_status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_corpus_identity_memories_corpus_identity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
