/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentMemoryRouteImport } from './routes/agent-memory'
import { Route as CurrentMigrationRouteImport } from './routes/current-migration'
import { Route as NewMigrationRouteImport } from './routes/new-migration'
import { Route as PastMigrationsRouteImport } from './routes/past-migrations'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMemoryRoute = AgentMemoryRouteImport.update({
  id: '/agent-memory',
  path: '/agent-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentMigrationRoute = CurrentMigrationRouteImport.update({
  id: '/current-migration',
  path: '/current-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const NewMigrationRoute = NewMigrationRouteImport.update({
  id: '/new-migration',
  path: '/new-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const PastMigrationsRoute = PastMigrationsRouteImport.update({
  id: '/past-migrations',
  path: '/past-migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-memory': typeof AgentMemoryRoute
  '/current-migration': typeof CurrentMigrationRoute
  '/new-migration': typeof NewMigrationRoute
  '/past-migrations': typeof PastMigrationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-memory': typeof AgentMemoryRoute
  '/current-migration': typeof CurrentMigrationRoute
  '/new-migration': typeof NewMigrationRoute
  '/past-migrations': typeof PastMigrationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-memory': typeof AgentMemoryRoute
  '/current-migration': typeof CurrentMigrationRoute
  '/new-migration': typeof NewMigrationRoute
  '/past-migrations': typeof PastMigrationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-memory'
    | '/current-migration'
    | '/new-migration'
    | '/past-migrations'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-memory'
    | '/current-migration'
    | '/new-migration'
    | '/past-migrations'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/agent-memory'
    | '/current-migration'
    | '/new-migration'
    | '/past-migrations'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentMemoryRoute: typeof AgentMemoryRoute
  CurrentMigrationRoute: typeof CurrentMigrationRoute
  NewMigrationRoute: typeof NewMigrationRoute
  PastMigrationsRoute: typeof PastMigrationsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-memory': {
      id: '/agent-memory'
      path: '/agent-memory'
      fullPath: '/agent-memory'
      preLoaderRoute: typeof AgentMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-migration': {
      id: '/current-migration'
      path: '/current-migration'
      fullPath: '/current-migration'
      preLoaderRoute: typeof CurrentMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-migration': {
      id: '/new-migration'
      path: '/new-migration'
      fullPath: '/new-migration'
      preLoaderRoute: typeof NewMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-migrations': {
      id: '/past-migrations'
      path: '/past-migrations'
      fullPath: '/past-migrations'
      preLoaderRoute: typeof PastMigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentMemoryRoute: AgentMemoryRoute,
  CurrentMigrationRoute: CurrentMigrationRoute,
  NewMigrationRoute: NewMigrationRoute,
  PastMigrationsRoute: PastMigrationsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
